// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yraukyzidybywalccuud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyYXVreXppZHlieXdhbGNjdXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODk4OTMsImV4cCI6MjA2ODI2NTg5M30.5FS8Cvm9dCj13qt0ksYls3u3Ahr77216k0OpGsFXN_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});